# YAML linting configuration for apqx-platform
# Relaxed configuration for GitOps and infrastructure files

extends: relaxed

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']