extends: default

rules:
  line-length:
    max: 150
    level: warning
  document-start: disable
  trailing-spaces: disable
  new-line-at-end-of-file: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']