# Sample application HPA - SRE Basics
# HorizontalPodAutoscaler with minimal scaling for SRE fundamentals

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: hpa
    app.kubernetes.io/part-of: apqx-platform
  annotations:
    # SRE: HPA configuration for basic scaling
    sre.io/scaling-policy: "cpu-based"
    sre.io/target-availability: "99.9%"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  # SRE Basics: Minimal scaling 1-3 replicas
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
