# Base Kustomization for sample application
# Defines the base resources for the sample Go application

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: sample-app
  app.kubernetes.io/part-of: apqx-platform
  app.kubernetes.io/managed-by: argocd

images:
- name: ghcr.io/example/sample-app
  newTag: "sha256:c6dd9ced0f39574019121caa889cb0e3f33707f957f1cd50ade4c2255abf8799"
