# PodDisruptionBudget for sample-app
# Ensures availability during cluster maintenance and rolling updates
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: pdb
    app.kubernetes.io/part-of: apqx-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app