# RoleBinding for sample-app ServiceAccount
# Grants the minimal Role permissions to the ServiceAccount

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: apqx-platform
subjects:
- kind: ServiceAccount
  name: sample-app
  namespace: sample-app
roleRef:
  kind: Role
  name: sample-app
  apiGroup: rbac.authorization.k8s.io