# Sample application service
# ClusterIP service for the sample Go application

apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: apqx-platform
  annotations:
    # SRE: Service monitoring annotations
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
    # Tailscale: Expose service via MagicDNS
    tailscale.com/expose: "true"
    tailscale.com/hostname: "app-onprem"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: sample-app
