apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: apqx-platform
automountServiceAccountToken: false