# Kyverno Policy: Require Resource Requests/Limits
# Enforces CPU and memory requests/limits on all deployments

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources
spec:
  validationFailureAction: Enforce
  rules:
    - name: requests-limits-required
      match:
        any:
          - resources:
              kinds:
                - Deployment
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - cert-manager
                - kyverno
                - argocd
      validate:
        message: "CPU/Memory requests & limits are required"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - resources:
                      requests:
                        cpu: "?*"
                        memory: "?*"
                      limits:
                        cpu: "?*"
                        memory: "?*"
