# Kyverno Policy: Require Health Probes
# Enforces liveness and readiness probes on all deployments

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
spec:
  validationFailureAction: Enforce
  rules:
    - name: probes-required
      match:
        any:
          - resources:
              kinds:
                - Deployment
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - cert-manager
                - kyverno
                - argocd
                - tailscale
      validate:
        message: "Liveness/Readiness probes are required"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - livenessProbe: {}
                    readinessProbe: {}
