# GolangCI-Lint configuration for apqx-platform
# Configuration for Go code linting and quality checks

version: 2

run:
  timeout: 5m
  go-version: '1.21'
  modules-download-mode: readonly

linters:
  presets:
    - bugs
    - unused
    - format
  disable:
    - gosec  # Run separately

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
