# Sample application GitOps manifest
# Argo CD application for the sample Go application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: "true"
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/part-of: apqx-platform
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/j0c2/apqx-platform.git
    path: gitops/apps/app/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  # Ignore differences for fields managed by Argo Rollouts controller
  ignoreDifferences:
  - group: ""
    kind: Service
    name: sample-app-stable
    jsonPointers:
    - /spec/selector
  - group: ""
    kind: Service  
    name: sample-app-canary
    jsonPointers:
    - /spec/selector
  revisionHistoryLimit: 3
