# Certificate for sample-app TLS
# Generates self-signed TLS certificate for sslip.io domain

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-app-cert
  namespace: sample-app
spec:
  secretName: sample-app-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - app.*********sslip.io
