apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-tailscale
  namespace: sample-app
spec:
  ingressClassName: tailscale
  # First label here becomes "app-onprem.<tailnet>.ts.net"
  tls:
    - hosts:
        - app-onprem
  defaultBackend:
    service:
      name: sample-app
      port:
        number: 80
