# Development overlay Kustomization for sample application
# Environment-specific configuration for development

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
- replica-patch.yaml

images:
- name: ghcr.io/example/sample-app
  newTag: dev-latest
