# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- ingress.yaml
- secret.yaml
- clusterissuer-selfsigned.yaml
- certificate.yaml

# Image configuration - digest will be updated by CI pipeline
images:
- digest: sha256:3806eda9fca39890e16dce3290f7494f1225d8c136c0f8bb45154b2ce0e070ce
  name: ghcr.io/j0c2/apqx-platform/sample-app

labels:
- pairs:
    environment: dev
