# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- service-stable.yaml
- service-canary.yaml
- rollout.yaml
- ingress.yaml
- secret.yaml
- certificate.yaml
- ts-egress-externalname.yaml
- ingress-tailscale.yaml

# Patch HPA to reference Rollout instead of Deployment
patches:
- patch: |-
    - op: replace
      path: /spec/scaleTargetRef/apiVersion
      value: argoproj.io/v1alpha1
    - op: replace
      path: /spec/scaleTargetRef/kind
      value: Rollout
  target:
    kind: HorizontalPodAutoscaler
    name: sample-app

# Image configuration - digest will be updated by CI pipeline
images:
- digest: sha256:7f69039539f3e19958d579576ab79ca93995ff2065a9d8361db86ba885ae3f3f
  name: ghcr.io/j0c2/apqx-platform/sample-app

labels:
- pairs:
    environment: dev
