# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- service-stable.yaml
- service-canary.yaml
- rollout.yaml
- ingress.yaml
- secret.yaml
- clusterissuer-selfsigned.yaml
- certificate.yaml
- ts-egress-externalname.yaml
- ingress-tailscale.yaml

# Image configuration - digest will be updated by CI pipeline
images:
- digest: sha256:a544984754e8600d62d291b03a6b6869758bd5910aab3f6bc1c5f237fa474369
  name: ghcr.io/j0c2/apqx-platform/sample-app

labels:
- pairs:
    environment: dev
