# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- service-stable.yaml
- service-canary.yaml
- rollout.yaml
- ingress.yaml
- secret.yaml
- clusterissuer-selfsigned.yaml
- certificate.yaml
- ts-egress-externalname.yaml
- ingress-tailscale.yaml

# Image configuration - digest will be updated by CI pipeline
images:
- digest: sha256:e4e9145a46fae017ab2f7dc9ae37ea8d942fd0d4a300a86bb42312ef172d7ba5
  name: ghcr.io/j0c2/apqx-platform/sample-app

labels:
- pairs:
    environment: dev
