apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

    # newTag will be replaced by CI with the immutable digest (e.g., sha256:abc...)
images:
- name: ghcr.io/example/sample-app
  newName: ghcr.io/example/sample-app
  newTag: sha256:PLACEHOLDER
- digest: sha256:22b6d6f623936e1e0efacda5aadd8de13a51da1f89003ed31115ca5de1228895
  name: ghcr.io/j0c2/apqx-platform/sample-app
