# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- ingress.yaml

# Image configuration - digest will be updated by CI pipeline
images:
- digest: sha256:5951a7f636512cc7442507c6f3a89e4747be108b64af86d9b092976861eb1bd7
  name: ghcr.io/j0c2/apqx-platform/sample-app

labels:
- pairs:
    environment: dev
