# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- service-stable.yaml
- service-canary.yaml
- rollout.yaml
- ingress.yaml
- secret.yaml
- clusterissuer-selfsigned.yaml
- certificate.yaml

# Image configuration - digest will be updated by CI pipeline
images:
- digest: sha256:5bc481d80d5eb31e781f8ebedc6cd61d3241f4321c197cd058d6456d04d4598c
  name: ghcr.io/j0c2/apqx-platform/sample-app

labels:
- pairs:
    environment: dev
