# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- service-stable.yaml
- service-canary.yaml
- rollout.yaml
- ingress.yaml
- secret.yaml
- certificate.yaml
- ts-egress-externalname.yaml
- ingress-tailscale.yaml

# Image configuration - digest will be updated by CI pipeline
images:
- digest: sha256:e7d9041a9ddb1ef1696167a0a837c8b664174806e88315c7b78688c0bdc058a8
  name: ghcr.io/j0c2/apqx-platform/sample-app

labels:
- pairs:
    environment: dev
