# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- ingress.yaml
- secret.yaml

# Image configuration - digest will be updated by CI pipeline
images:
- name: ghcr.io/j0c2/apqx-platform/sample-app
  digest: sha256:placeholder

labels:
- pairs:
    environment: dev
