# Dev overlay for sample application
# Customizations specific to the development environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
- ../../base
- service-stable.yaml
- service-canary.yaml
- rollout.yaml
- ingress.yaml
- secret.yaml
- clusterissuer-selfsigned.yaml
- certificate.yaml

# Image configuration - digest will be updated by CI pipeline
images:
- digest: sha256:db1c746cf268b7f2b394213177bc28024ae7cf605e8119175c96a77a532816a9
  name: ghcr.io/j0c2/apqx-platform/sample-app

labels:
- pairs:
    environment: dev
