configs:
  params:
    server.insecure: true
dex:
  enabled: false

server:
  ingress:
    enabled: false  # We'll manage ingress via GitOps
  service:
    type: ClusterIP
  extraArgs:
    - --insecure
