# Argo Rollouts configuration
# Progressive delivery controller settings

dashboard:
  enabled: false

installCRDs: true

controller:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m" 
    limits:
      memory: "128Mi"
      cpu: "100m"