apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/part-of: apqx-platform
spec:
  project: default
  source:
    repoURL: https://github.com/j0c2/apqx-platform.git
    targetRevision: main
    path: gitops/apps/app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10