# ArgoCD TLS Certificate
# Self-signed certificate for ArgoCD HTTPS access

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: apqx-platform
    app.kubernetes.io/component: certificate
spec:
  secretName: argocd-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - argocd.localhost