apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/j0c2/apqx-platform.git
    targetRevision: HEAD
    path: gitops/infrastructure/cert-manager
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
