apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingresses
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/j0c2/apqx-platform.git
    targetRevision: HEAD
    path: gitops/apps/ingresses
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
