# GitHub Actions Self-Hosted Runner via Docker Compose
# Provides ephemeral runner for local development and testing
# Usage: docker compose --env-file .env up -d

version: "3.9"

services:
  actions-runner:
    image: ghcr.io/myoung34/github-runner:2.317.0  # pinned for reproducibility
    container_name: actions-runner
    environment:
      REPO_URL: ${REPO_URL}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_LABELS: ${RUNNER_LABELS}
      RUNNER_GROUP: Default
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      EPHEMERAL: "1"                    # Runner auto-unregisters when stopped
      RUNNER_WORKDIR: /tmp/runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker builds
    networks:
      - runner-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'Runner.Listener' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  runner-network:
    driver: bridge