apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ingressClassName: traefik
  tls:
    - hosts: [ "argocd.192.168.50.53.sslip.io" ]
      secretName: argocd-sslip-tls
  rules:
    - host: argocd.192.168.50.53.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
