apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rollouts-dashboard
  namespace: argo-rollouts
spec:
  ingressClassName: traefik
  tls:
    - hosts: [ "rollouts.192.168.50.53.sslip.io" ]
      secretName: rollouts-sslip-tls
  rules:
    - host: rollouts.192.168.50.53.sslip.io
      http:
        paths:
          - path: /rollouts/
            pathType: Prefix
            backend:
              service:
                name: argo-rollouts-dashboard
                port:
                  number: 3100
