apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: sample-app
spec:
  ingressClassName: traefik
  tls:
    - hosts: [ "app.192.168.50.53.sslip.io" ]
      secretName: app-sslip-tls
  rules:
    - host: app.192.168.50.53.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app-stable
                port:
                  number: 80
